#!/usr/bin/env bash 
pushd $HOME/.dotfiles
STOW_FOLDERS="nvim,zsh,bin,tmux,uwuntu,i3"

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done

popd

