#!/usr/bin/env bash
addToPathFront /home/usama/n/bin

addToPath /home/usama/personal/lua-language-server/bin/Linux
addToPath /usr/local/go/bin
addToPath $GOPATH/bin

addToPath $HOME/.yarn/bin
addToPath /usr/lib/llvm-8/bin

addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup

addToPathFront $HOME/.local/.npm-global/bin
addToPathFront $HOME/.local/bin
addToPathFront $HOME/.local/go/bin
addToPathFront $HOME/.local/scripts
addToPathFront $HOME/go/bin
